(()=>{"use strict";
const DB=window.PRICE_DB||{meta:{},suppliers:[],priceLists:[],categories:[],products:[]};
const $=id=>document.getElementById(id),num=v=>{const n=Number(String(v??"").replace(",","."));return Number.isFinite(n)?n:0},fmt=(v,d=2)=>new Intl.NumberFormat("ru-BY",{minimumFractionDigits:d,maximumFractionDigits:d}).format(Number.isFinite(v)?v:0),money=new Intl.NumberFormat("ru-BY",{minimumFractionDigits:2,maximumFractionDigits:2});
const state={mode:"rect",points:[],closed:false,extras:[],last:null};
const E={area:$("areaMetric"),per:$("perimeterMetric"),profile:$("profileSelect"),profileHint:$("profileHint"),supplier:$("supplierSelect"),rate:$("usdRate"),membrane:$("membranePrice"),labor:$("laborPrice"),waste:$("wastePct"),room:$("roomName"),project:$("projectName"),client:$("clientPrice"),cost:$("costPrice"),profit:$("profitPrice"),margin:$("marginPct"),lines:$("resultLines"),rateWarn:$("rateWarning"),resultRoom:$("resultRoomName"),source:$("resultSource"),extraWrap:$("extraItemsWrap"),extraList:$("extraItems"),extraCount:$("extraItemsCount")};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function toast(t){const n=$("toast");n.textContent=t;n.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove("show"),1800)}
function dealer(p){if(!p)return null;const a=(p.prices||[]).filter(x=>x.price_type==="dealer");return a.find(x=>!x.variant)||a[0]||null}
function reference(p){return p?.prices?.find(x=>x.price_type==="mrc")||p?.prices?.find(x=>x.price_type==="rrp")||null}
function product(id){return DB.products.find(p=>p.id===Number(id))}
function category(id){return DB.categories.find(c=>c.id===Number(id))}
function initDB(){
 $("heroProducts").textContent=DB.meta.productCount??DB.products.length;$("heroPrices").textContent=DB.meta.priceCount??DB.products.reduce((s,p)=>s+(p.prices?.length||0),0);
 const dates=[...new Set(DB.priceLists.map(x=>x.effective_date).filter(Boolean))].sort();$("priceDates").textContent="Прайсы: "+(dates.join(" / ")||"локальные");
 E.supplier.innerHTML=DB.suppliers.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join("");
 const cats=new Set(DB.categories.filter(c=>c.parent_id===1).map(c=>c.id));
 const profiles=DB.products.filter(p=>{const d=dealer(p),u=(d?.unit||p.default_unit||"").toLowerCase();return (p.category_ids||[p.category_id]).some(id=>cats.has(id))&&d&&u.includes("м.п")});
 E.profile.innerHTML='<option value="">Без профиля</option>'+profiles.map(p=>{const d=dealer(p),r=reference(p);return `<option value="${p.id}">${esc(category(p.category_id)?.name||"")} — ${esc(p.name)} — ${fmt(d.amount)} ${d.currency}/${esc(d.unit||p.default_unit)}${r?` — МРЦ ${fmt(r.amount,0)} ${r.currency}`:""}</option>`}).join("");
 initCatalog();
}
function triangle(a,b,c){if(a<=0||b<=0||c<=0||a+b<=c||a+c<=b||b+c<=a)return NaN;const s=(a+b+c)/2;return Math.sqrt(Math.max(0,s*(s-a)*(s-b)*(s-c)))}
function sketchGeom(){const p=state.points;if(p.length<2)return{area:0,perimeter:0};let per=0;for(let i=1;i<p.length;i++)per+=Math.hypot(p[i].x-p[i-1].x,p[i].y-p[i-1].y);if(state.closed&&p.length>2)per+=Math.hypot(p[0].x-p.at(-1).x,p[0].y-p.at(-1).y);let area=0;if(state.closed&&p.length>2){for(let i=0;i<p.length;i++){const j=(i+1)%p.length;area+=p[i].x*p[j].y-p[j].x*p[i].y}area=Math.abs(area)/2}return{area,perimeter:per}}
function geom(){if(state.mode==="rect"){const l=num($("length").value),w=num($("width").value);return{area:l*w,perimeter:l&&w?2*(l+w):0,valid:true}}if(state.mode==="quad"){const a=num($("sideA").value),b=num($("sideB").value),c=num($("sideC").value),d=num($("sideD").value),e=num($("diagonal").value),a1=triangle(a,b,e),a2=triangle(c,d,e),ok=Number.isFinite(a1)&&Number.isFinite(a2);$("quadError").classList.toggle("hidden",ok||!(a||b||c||d||e));$("quadError").textContent=ok?"":"Проверьте стороны и диагональ: должны получиться два корректных треугольника.";return{area:ok?a1+a2:0,perimeter:a&&b&&c&&d?a+b+c+d:0,valid:ok}}return{...sketchGeom(),valid:true}}
function unitBYN(p){const d=dealer(p);if(!d)return 0;return d.currency==="USD"?d.amount*num(E.rate.value):d.amount}
function calc(){const g=geom(),factor=1+Math.max(0,num(E.waste.value))/100,profile=product(E.profile.value),pd=dealer(profile),profileQty=g.perimeter*factor,profileCost=profileQty*unitBYN(profile),membraneQty=g.area*factor,membraneCost=membraneQty*num(E.membrane.value),laborCost=g.area*num(E.labor.value),light=num($("lightQty").value)*num($("lightPrice").value),pipe=num($("pipeQty").value)*num($("pipePrice").value),cornice=num($("corniceQty").value)*num($("cornicePrice").value),misc=num($("miscCost").value),catalog=state.extras.reduce((s,x)=>s+x.qty*unitBYN(product(x.productId)),0),cost=membraneCost+laborCost+profileCost+light+pipe+cornice+misc+catalog;
 const method=document.querySelector('input[name="priceMethod"]:checked')?.value||"percent",v=num($("priceMethodValue").value);let client=cost;if(method==="percent")client=cost*(1+v/100);else if(method==="fixed")client=cost+v;else client=v;const profit=client-cost,margin=client?profit/client*100:0;
 E.area.textContent=`${fmt(g.area)} м²`;E.per.textContent=`${fmt(g.perimeter)} м`;E.resultRoom.textContent=E.room.value.trim()||"Помещение";E.client.textContent=`${money.format(client)} BYN`;E.cost.textContent=`${money.format(cost)} BYN`;E.profit.textContent=`${money.format(profit)} BYN`;E.margin.textContent=`${fmt(margin,1)}%`;E.profit.style.color=profit<0?"#ff8a8a":"";
 const lines=[];if(g.area)lines.push(["Геометрия",`${fmt(g.area)} м² • ${fmt(g.perimeter)} м`]);if(membraneCost)lines.push([`Полотно ${fmt(membraneQty)} м²`,`${money.format(membraneCost)} BYN`]);if(profile)lines.push([profile.name,`${money.format(profileCost)} BYN`]);if(laborCost)lines.push([`Монтаж ${fmt(g.area)} м²`,`${money.format(laborCost)} BYN`]);if(light)lines.push([`Светоточки × ${num($("lightQty").value)}`,`${money.format(light)} BYN`]);if(pipe)lines.push([`Обход труб × ${num($("pipeQty").value)}`,`${money.format(pipe)} BYN`]);if(cornice)lines.push([`Карниз / ниша ${fmt(num($("corniceQty").value))} м`,`${money.format(cornice)} BYN`]);if(misc)lines.push(["Прочее",`${money.format(misc)} BYN`]);if(catalog)lines.push([`Позиции из прайса (${state.extras.length})`,`${money.format(catalog)} BYN`]);E.lines.innerHTML=lines.length?lines.map(x=>`<div class="line-item"><span>${esc(x[0])}</span><strong>${esc(x[1])}</strong></div>`).join(""):'<div class="line-item"><span>Заполните параметры сметы</span><strong>—</strong></div>';
 const needRate=(pd?.currency==="USD")||state.extras.some(x=>dealer(product(x.productId))?.currency==="USD");E.rateWarn.classList.toggle("hidden",!(needRate&&!num(E.rate.value)));if(profile&&pd){const r=reference(profile);E.profileHint.textContent=`Поставщик: ${fmt(pd.amount)} ${pd.currency}/${pd.unit||profile.default_unit}${r?` • МРЦ: ${fmt(r.amount)} ${r.currency}/${r.unit||""}`:""}`}else E.profileHint.textContent="Профиль не выбран.";E.source.textContent=`Источник цен: локальная БД LumFer.BY • ${DB.meta.productCount||DB.products.length} позиций / ${DB.meta.priceCount||"—"} цен.`;state.last={g,factor,profile,profileQty,profileCost,membraneQty,membraneCost,laborCost,light,pipe,cornice,misc,catalog,cost,client,profit,margin,method,v};
}
function setMode(m){state.mode=m;document.querySelectorAll(".seg").forEach(b=>{const a=b.dataset.mode===m;b.classList.toggle("active",a);b.setAttribute("aria-selected",a)});$("rectFields").classList.toggle("hidden",m!=="rect");$("quadFields").classList.toggle("hidden",m!=="quad");$("sketchFields").classList.toggle("hidden",m!=="sketch");calc()}
function draw(){const svg=$("sketchSvg"),W=600,H=420,S=50,g=[];for(let x=0;x<=W;x+=12.5)g.push(`<line x1="${x}" y1="0" x2="${x}" y2="${H}" stroke="${x%50===0?'#253340':'#17212a'}" stroke-width="${x%50===0?1.2:.6}"/>`);for(let y=0;y<=H;y+=12.5)g.push(`<line x1="0" y1="${y}" x2="${W}" y2="${y}" stroke="${y%50===0?'#253340':'#17212a'}" stroke-width="${y%50===0?1.2:.6}"/>`);const pts=state.points.map(p=>`${p.x*S},${p.y*S}`).join(" "),poly=state.points.length?`<polyline points="${pts}${state.closed?' '+state.points[0].x*S+','+state.points[0].y*S:''}" fill="${state.closed?'rgba(183,255,90,.08)':'none'}" stroke="#b7ff5a" stroke-width="3"/>`:"",dots=state.points.map((p,i)=>`<circle cx="${p.x*S}" cy="${p.y*S}" r="6" fill="#b7ff5a"/><text x="${p.x*S+9}" y="${p.y*S-9}" fill="#dce4ec" font-size="12">${i+1}</text>`).join("");svg.innerHTML=`<rect width="${W}" height="${H}" fill="#091016"/>${g.join("")}${poly}${dots}<text x="12" y="408" fill="#61707f" font-size="11">1 крупная клетка = 1 м • шаг = 0,25 м</text>`}
function addPoint(e){if(state.closed)return;const r=$("sketchSvg").getBoundingClientRect(),snap=v=>Math.max(0,Math.round(v/.25)*.25);state.points.push({x:snap((e.clientX-r.left)/r.width*12),y:snap((e.clientY-r.top)/r.height*8.4)});draw();calc()}
function renderExtras(){E.extraWrap.classList.toggle("hidden",!state.extras.length);E.extraCount.textContent=state.extras.length;E.extraList.innerHTML=state.extras.map((x,i)=>{const p=product(x.productId),d=dealer(p);return `<div class="extra-row"><div class="extra-name">${esc(p?.name||"Позиция")}<small>${d?`${fmt(d.amount)} ${d.currency}/${esc(d.unit||p.default_unit)}`:"цена не найдена"}</small></div><input data-q="${i}" type="number" min="0" step="0.01" value="${x.qty}"><div style="text-align:right;font-size:11px;color:#83909d">${esc(p?.default_unit||"шт.")}</div><button class="remove-btn" data-x="${i}" type="button">×</button></div>`}).join("");E.extraList.querySelectorAll("[data-q]").forEach(n=>n.oninput=()=>{state.extras[+n.dataset.q].qty=Math.max(0,num(n.value));calc()});E.extraList.querySelectorAll("[data-x]").forEach(n=>n.onclick=()=>{state.extras.splice(+n.dataset.x,1);renderExtras();calc()})}
function addProduct(id){const p=product(id);if(!dealer(p)){toast("У позиции нет дилерской цены");return}const x=state.extras.find(e=>e.productId===id);x?x.qty++:state.extras.push({productId:id,qty:1});renderExtras();calc();toast("Позиция добавлена")}
function initCatalog(){const c=$("catalogCategory");c.innerHTML='<option value="">Все категории</option>'+DB.categories.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("");const render=()=>{const q=$("catalogSearch").value.trim().toLowerCase(),cid=+c.value||0,a=DB.products.filter(p=>(!cid||(p.category_ids||[p.category_id]).includes(cid))&&(!q||p.name.toLowerCase().includes(q))).slice(0,100);$("catalogMeta").textContent=`Показано ${a.length} из ${DB.products.length} позиций. Дилерская цена используется в себестоимости; МРЦ/РРЦ — справочно.`;$("catalogList").innerHTML=a.map(p=>`<article class="catalog-card"><h4>${esc(p.name)}</h4><div class="category">${esc(category((p.category_ids||[p.category_id])[0])?.name||"Без категории")}</div><div class="catalog-prices">${(p.prices||[]).map(r=>`<span class="price-pill ${r.price_type==='dealer'?'dealer':''}">${esc(r.price_type.toUpperCase())}: ${fmt(r.amount)} ${r.currency}${r.variant?` • ${esc(r.variant)}`:""}</span>`).join("")}</div><footer><small>${esc(p.default_unit||"шт.")}</small><button class="button small secondary" data-add="${p.id}" type="button">Добавить</button></footer></article>`).join("");$("catalogList").querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addProduct(+b.dataset.add))};$("catalogSearch").oninput=render;c.onchange=render;render()}
function openDialog(id){const d=$(id);typeof d.showModal==="function"?d.showModal():d.setAttribute("open","");if(id==="savedDialog")renderSaved()}
function closeDialog(id){const d=$(id);d.close?.();d.removeAttribute("open")}
function snapshot(){calc();return{version:2,id:Date.now(),savedAt:new Date().toISOString(),project:E.project.value.trim(),room:E.room.value.trim(),mode:state.mode,inputs:{length:$("length").value,width:$("width").value,sideA:$("sideA").value,sideB:$("sideB").value,sideC:$("sideC").value,sideD:$("sideD").value,diagonal:$("diagonal").value,points:state.points,closed:state.closed,usdRate:E.rate.value,profileId:E.profile.value,membrane:E.membrane.value,labor:E.labor.value,waste:E.waste.value,lightQty:$("lightQty").value,lightPrice:$("lightPrice").value,pipeQty:$("pipeQty").value,pipePrice:$("pipePrice").value,corniceQty:$("corniceQty").value,cornicePrice:$("cornicePrice").value,misc:$("miscCost").value,method:document.querySelector('input[name="priceMethod"]:checked')?.value||"percent",methodValue:$("priceMethodValue").value,extras:state.extras},result:state.last?{area:state.last.g.area,perimeter:state.last.g.perimeter,cost:state.last.cost,client:state.last.client,profit:state.last.profit,margin:state.last.margin}:null,priceDb:{supplier:"LumFer.BY",products:DB.products.length,prices:DB.meta.priceCount}}}
function save(){const a=JSON.parse(localStorage.getItem("ceiling_estimates_v2")||"[]"),x=snapshot();a.unshift(x);localStorage.setItem("ceiling_estimates_v2",JSON.stringify(a.slice(0,100)));toast("Смета сохранена на устройстве")}
function renderSaved(){const a=JSON.parse(localStorage.getItem("ceiling_estimates_v2")||"[]"),w=$("savedList");if(!a.length){w.innerHTML='<div class="saved-card"><h4>Смет пока нет</h4><p>Сохранённые расчёты появятся здесь.</p></div>';return}w.innerHTML=a.map((x,i)=>`<article class="saved-card"><div class="saved-card-head"><div><h4>${esc(x.room||"Помещение")}</h4><p>${esc(x.project||"Без объекта")} • ${new Date(x.savedAt).toLocaleString("ru-BY")}</p></div><div class="saved-total">${money.format(x.result?.client||0)} BYN</div></div><div class="saved-actions"><button class="button small secondary" data-load="${i}">Открыть</button><button class="button small ghost" data-del="${i}">Удалить</button></div></article>`).join("");w.querySelectorAll("[data-load]").forEach(b=>b.onclick=()=>load(a[+b.dataset.load]));w.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{a.splice(+b.dataset.del,1);localStorage.setItem("ceiling_estimates_v2",JSON.stringify(a));renderSaved()})}
function load(x){const i=x.inputs||{};E.project.value=x.project||"";E.room.value=x.room||"";setMode(x.mode||"rect");for(const [k,id] of Object.entries({length:"length",width:"width",sideA:"sideA",sideB:"sideB",sideC:"sideC",sideD:"sideD",diagonal:"diagonal",usdRate:"usdRate",profileId:"profileSelect",membrane:"membranePrice",labor:"laborPrice",waste:"wastePct",lightQty:"lightQty",lightPrice:"lightPrice",pipeQty:"pipeQty",pipePrice:"pipePrice",corniceQty:"corniceQty",cornicePrice:"cornicePrice",misc:"miscCost",methodValue:"priceMethodValue"}))if(i[k]!==undefined)$(id).value=i[k];state.points=Array.isArray(i.points)?i.points:[];state.closed=!!i.closed;state.extras=Array.isArray(i.extras)?i.extras:[];const r=document.querySelector(`input[name="priceMethod"][value="${i.method||'percent'}"]`);if(r)r.checked=true;draw();renderExtras();methodUI();calc();closeDialog("savedDialog");location.hash="calculator"}
function methodUI(){const m=document.querySelector('input[name="priceMethod"]:checked')?.value||"percent";document.querySelectorAll(".method-card").forEach(c=>c.classList.toggle("active",c.querySelector("input").checked));$("priceMethodLabel").textContent=m==="percent"?"Наценка, %":m==="fixed"?"Фиксированная прибыль, BYN":"Цена клиенту, BYN";calc()}
function exportJSON(){const x=snapshot(),u=URL.createObjectURL(new Blob([JSON.stringify(x,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=u;a.download=`smeta-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function bind(){document.querySelectorAll(".seg").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));document.querySelectorAll("#calcForm input,#calcForm select").forEach(n=>n.addEventListener("input",calc));document.querySelectorAll('input[name="priceMethod"]').forEach(n=>n.onchange=methodUI);["openCatalogTop","openCatalogHero","openCatalogInline"].forEach(id=>$(id).onclick=()=>openDialog("catalogDialog"));$("openSavedTop").onclick=()=>openDialog("savedDialog");document.querySelectorAll("[data-close-dialog]").forEach(b=>b.onclick=()=>closeDialog(b.dataset.closeDialog));$("saveEstimate").onclick=save;$("printEstimate").onclick=()=>print();$("exportEstimate").onclick=exportJSON;$("sketchSvg").onpointerdown=addPoint;$("sketchUndo").onclick=()=>{state.closed?state.closed=false:state.points.pop();draw();calc()};$("sketchClose").onclick=()=>{if(state.points.length<3)return toast("Нужно минимум 3 точки");state.closed=true;draw();calc()};$("sketchClear").onclick=()=>{state.points=[];state.closed=false;draw();calc()}}
initDB();bind();draw();calc();
})();
